attempt to connect rspec and ruby files
pulibrary/ruby-checkpoint pull request #5
Opened 2024-06-26 15:32 UTC by vh8154

2024-06-26 17:59 UTC, vh8154 commented
This PR is related to Ruby Checkpoint project part 1.

2024-06-26 20:05 UTC, christinach requested changes
Great work @vh8154 ! can you please update the title of the PR and address a couple of comments I added?

2024-06-26 20:05 UTC, christinach commented on .byebug_history
> +c
Can you add this file in .gitignore so that git ignores it?

2024-06-26 20:05 UTC, christinach commented on spec/house_spec.rb
> +        # puts "Test File:\n" + test_file
Can you remove the comments `# puts ` unless you find them helpful for this project. You can always remove them in the end if you want to keep them until you finish the project.

2024-06-27 14:03 UTC, christinach approved these changes
Thanks @vh8154 !

2024-06-27 14:03 UTC, merged